server:
  #应用端口
  port: 8888
  context-path: /duowen-sms-rabbitmq/
spring:
  application:
    #指定应用名
    name: duowen-sms-rabbitmq
  boot:
    admin:
      context-path: admin #配置访问路径为：http://localhost:8888/duowen-sms-rabbitmq/admin
      client:
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
        url: http://localhost:8888/duowen-sms-rabbitmq # 向服务端注册的地址
management:
  port: 64001
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false
info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
#springcloud feign 请求超时处理
#请求处理的超时时间
ribbon:
  ReadTimeout: 4000
#请求连接的超时时间
  ConnectTimeout: 3000
#####################duowen个性化配置-开始####################################
duowen:
  feign:
    client:
      #调用地址
      url:
        # 本地地址
        localhost: http://localhost:8080/duowenapp_b
        dev: https://test.duowenlvshi.com/duowenapp_b
        product: https://b.duowenlvshi.com
        #正在使用的环境
        evn: http://localhost:8080/duowenapp_b
      app:
        e:
          evn: https://e.duowenlvshi.com
#duowen.feign.client.app.e.evn

  rabbitmq:
    #开发环境配置。
    dev:
      connectionFactory:
        host: 120.76.138.153
        port: 5672
        username: admin
        password: admin
        virtualHost: /
    #线上环境
    product:
        connectionFactory:
          host: 120.25.161.131
          port: 5672
          username: admin
          password: admin
          virtualHost: /

    #本地虚拟机
    localhost:
        connectionFactory:
          host: localhost
          port: 5672
          username: admin
          password: admin
          virtualHost: /
    #正在使用的环境
    evn:
        connectionFactory:
          host: 120.76.138.153
          port: 5672
          username: admin
          password: admin
          virtualHost: /
    #交换机
    exchanges:
      smsExchangeName: sms #短信
      smDelayedExchangeName: sms_delayed #定时短信发送
      monitorScheduleExchangeName: monitorScheduleExchangeName #调度监控
      lawyerCooperationMessageExchangeName: lawyerCooperationMessage #律师合作 发送app消息
      delayedLawyerCooperationMessageExchangeName: delayedLawyerCooperationMessage #律师合作延时发送app消息
    queues:
      #smsExchangeName 立即发送短信消息
      immediate: immediate
      #smDelayedExchangeName 延迟发送短信消息
      delayed: delayed
      #smDelayedExchangeName 延迟发送短信消息,重新处理
      smsDelayedAfterRepeat: smsDelayedAfterRepeat
      #律师合作 发送app消息
      appMessage: appMessage
      #律师合作 延迟发送app消息
      delayedAppMessage: delayedAppMessage
      #律师合作 延迟发送app消息,重新处理
      delayedAppMessageRepeat: delayedAppMessageRepeat
    #立即发送消息
    routingKey:
      smsRootingKey: sms
      smDelayedKey: sms_delayed
      appMessageKey: appMessage
      delayedAppMessageKey: delayedAppMessage
      delayedAppMessageRepeatKey: delayedAppMessageRepeat
#####################duowen个性化配置-结束####################################
